# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml
# See options: https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/README.md

global:
  ingress:
    enabled: true
    className: nginx
    host: "dnslabel.location.cloudapp.azure.com"
    tls:
      enabled: true
      secretName: "tls-secret"
  image:
      tag: 8.1.3
      # tag: latest
      # pullPolicy: Always
  identity:
    auth:
      publicIssuerUrl: "https://dnslabel.location.cloudapp.azure.com/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://dnslabel.location.cloudapp.azure.com/operate"
      tasklist:
        redirectUrl: "https://dnslabel.location.cloudapp.azure.com/tasklist"
      optimize:
        redirectUrl: "https://dnslabel.location.cloudapp.azure.com/optimize"

operate:
  contextPath: "/operate"

tasklist:
  contextPath: "/tasklist"

optimize:
  contextPath: "/optimize"

identity:
  contextPath: "/identity"
  fullURL: "https://dnslabel.location.cloudapp.azure.com/identity"
  
  keycloak:
    extraEnvVars:
      - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_FRONTEND_URL
        value: "https://dnslabel.location.cloudapp.azure.com/auth"

zeebe-gateway:
  logLevel: DEBUG
  ingress:
    enabled: true
    host: "dnslabel.location.cloudapp.azure.com"
    tls:
      enabled: true
      secretName: "tls-secret"
# reduced resources for non-prod use
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2048Mi"
      cpu: "1000m"   
# add interceptor jar and configuration to pod
  extraVolumes:
  - name: interceptors
    emptyDir: {}
  - name: kc-interceptor-config
    configMap:
      name: zb-kc-interceptor-config
      items:
      - key: "zeebe-keycloak.json"
        path: "zeebe-keycloak.json"
  extraInitContainers:
  - name: init-interceptors
    image: busybox
    command: ['/bin/sh', '-c']
    args: ['wget -qO- --no-check-certificate https://github.com/camunda-community-hub/zeebe-keycloak-interceptor/releases/download/1.2.11/zeebe-keycloak-interceptor-1.2.11.zip | busybox unzip -j -d /interceptors - *jar-with-dependencies.jar && ls -al /interceptors']
    volumeMounts:
      - mountPath: /interceptors
        name: interceptors
  # configure interceptor
  env:
  - name: ZEEBE_GATEWAY_INTERCEPTORS_0_ID
    value: "keycloak"
  - name: ZEEBE_GATEWAY_INTERCEPTORS_0_JARPATH
    value: /interceptors/zeebe-keycloak-interceptor-1.2.11-jar-with-dependencies.jar
  - name: ZEEBE_GATEWAY_INTERCEPTORS_0_CLASSNAME
    value: "org.camunda.community.zeebe.keycloak.interceptor.ZeebeKeycloakInterceptor"
  - name: ZEEBE_GATEWAY_SECURITY_KEYCLOAK_CONFIG_PATH
    value: /usr/local/zeebe/config/zeebe-keycloak.json
  # enable remote debugging
  - name: JAVA_TOOL_OPTIONS
    value: '-Xdebug -agentlib:jdwp=transport=dt_socket,address=0.0.0.0:9991,server=y,suspend=n'
  extraVolumeMounts:
  - mountPath: /interceptors
    name: interceptors
  - mountPath: /usr/local/zeebe/config/zeebe-keycloak.json
    subPath: zeebe-keycloak.json
    name: kc-interceptor-config

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 1Gi

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "2Gi"
  
elasticsearch:
  enabled: true
  imageTag: 7.17.3
  replicas: 1
  minimumMasterNodes: 1
  # Allow no backup for single node setups
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  